/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_simley_ndk_day78_fmod_FmodActivity */

#include "fmod/fmod.hpp"
#include <string>

#ifndef _Included_com_simley_ndk_day78_fmod_FmodActivity
#define _Included_com_simley_ndk_day78_fmod_FmodActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_simley_ndk_day78_fmod_FmodActivity_MODE_NORMAL
#define com_simley_ndk_day78_fmod_FmodActivity_MODE_NORMAL 0L
#undef com_simley_ndk_day78_fmod_FmodActivity_MODE_LUOLI
#define com_simley_ndk_day78_fmod_FmodActivity_MODE_LUOLI 1L
#undef com_simley_ndk_day78_fmod_FmodActivity_MODE_DASHU
#define com_simley_ndk_day78_fmod_FmodActivity_MODE_DASHU 2L
#undef com_simley_ndk_day78_fmod_FmodActivity_MODE_JINGSONG
#define com_simley_ndk_day78_fmod_FmodActivity_MODE_JINGSONG 3L
#undef com_simley_ndk_day78_fmod_FmodActivity_MODE_GAOGUAI
#define com_simley_ndk_day78_fmod_FmodActivity_MODE_GAOGUAI 4L
#undef com_simley_ndk_day78_fmod_FmodActivity_MODE_KONGLING
#define com_simley_ndk_day78_fmod_FmodActivity_MODE_KONGLING 5L
/*
 * Class:     com_simley_ndk_day78_fmod_FmodActivity
 * Method:    voiceChangeNative
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_simley_ndk_1day78_fmod_FmodActivity_voiceChangeNative
        (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
