/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_serialport_api_SerialPort */

#ifndef _Included_qingwei_kong_serialportlibrary_SerialPort
#define _Included_qingwei_kong_serialportlibrary_SerialPort
#ifdef __cplusplus
extern "C" {
#endif

/* 关闭串口
 * Class:     android_serialport_api_SerialPort
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL
Java_com_simley_ndk_1day78_serialport_SerialPort_closeNative(JNIEnv *env, jobject thiz);

/* 通过串口的波特率等信息，构建Java对象-FileDescriptor
 * Class:     android_serialport_api_SerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL
Java_com_simley_ndk_1day78_serialport_SerialPort_openNative(JNIEnv *env, jobject thiz, jstring path,
                                                            jint baud_rate, jint flags);

#ifdef __cplusplus
}
#endif
#endif


